theme: jekyll-theme-architect
url: http://newblog.gemustudio.com/
name: Good Developer
description: Blog programistyczy.
plugins: ['jekyll-twitter-plugin']

author: Krzysztof Owsiany
author_email: gocom@o2.pl

