theme: jekyll-theme-architect
url: http://godev.gemustudio.com
name: Good Developer
description: Blog programistyczy.
plugins: [
  'jekyll-twitter-plugin',
  'jekyll-seo-tag',
  'jekyll-tagging',
  'jekyll-sitemap',
  'jekyll-paginate',
  'jekyll-youtube'
  
]

author: Krzysztof Owsiany
author_email: gocom@o2.pl

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
tag_page_data:
  sitemap: false

  mailchimp-list: //redgadgets.us10.list-manage.com/subscribe/post?u=2123c1f8978fd64d7bf7612072d81977a-us15;id=32b5575059"


paginate: 10
paginate_path:       '/page:num/'

google_analytics: UA-93197123-1
disqus: godev